import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
  <div className="flex min-h-screen">

    {/* SIDEBAR */}
    <aside className="w-64 bg-slate-900 text-white p-4 space-y-4">
      <h2 className="text-xl font-bold mb-4">
        Sistema Asamblea
      </h2>

      <nav className="space-y-2">
        <a href="/" className="block hover:bg-slate-700 p-2 rounded">
          Dashboard
        </a>

        <a href="/historial" className="block hover:bg-slate-700 p-2 rounded">
          Historial de Asambleas
        </a>
      </nav>
    </aside>

    {/* CONTENIDO */}
    <main className="flex-1 bg-slate-100 p-6">
      {children}
    </main>

  </div>
</body>
    </html>
  );
}
